# Generated by Django 5.2.3 on 2025-06-18 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imobiliaria',
            options={},
        ),
    ]
