# Generated by Django 5.2.3 on 2025-06-17 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empreendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text="URL amigável, ex: 'meu-empreendimento-incrivel'", max_length=255, unique=True)),
                ('tipo_empreendimento', models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal'), ('loteamento', 'Loteamento')], max_length=20)),
                ('uso', models.CharField(choices=[('residencial', 'Residencial'), ('comercial', 'Comercial'), ('misto', 'Misto')], max_length=20)),
                ('status_empreendimento', models.CharField(choices=[('breve_lancamento', 'Breve Lançamento'), ('lancamento', 'Lançamento'), ('em_obras', 'Em Obras'), ('pronto', 'Pronto para morar')], max_length=20)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('descricao_curta', models.CharField(help_text='Um resumo atrativo do empreendimento.', max_length=300)),
                ('tipo_anunciante', models.CharField(help_text='Construtora, Incorporadora, etc.', max_length=50)),
                ('nome_anunciante', models.CharField(max_length=255)),
                ('descricao_anunciante', models.TextField(blank=True, max_length=500)),
                ('cep', models.CharField(max_length=9)),
                ('endereco_completo', models.CharField(max_length=512)),
                ('url_Maps', models.URLField(help_text='Link para o mapa embedado.', max_length=2048)),
                ('thumbnail_localizacao', models.ImageField(upload_to='empreendimentos/thumbnails_mapa/')),
                ('numero_whatsapp_atendimento', models.CharField(max_length=15)),
                ('limite_reservas_canal', models.PositiveIntegerField(blank=True, help_text='Nº máx. de reservas ativas por corretor/imobiliária', null=True)),
                ('anunciante_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empreendimentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Amenidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('icone', models.CharField(blank=True, help_text='Nome do ícone de uma biblioteca como Material Icons', max_length=50)),
                ('empreendimentos', models.ManyToManyField(blank=True, related_name='amenidades', to='empreendimentos.empreendimento')),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('apartamento', 'Apartamento'), ('studio', 'Studio'), ('cobertura', 'Cobertura'), ('lote', 'Lote'), ('sala', 'Sala')], max_length=50)),
                ('metragem', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quartos', models.PositiveIntegerField(default=0)),
                ('banheiros', models.PositiveIntegerField(default=0)),
                ('vagas', models.PositiveIntegerField(default=0)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('reservada', 'Reservada'), ('vendida', 'Vendida'), ('indisponivel', 'Indisponível')], default='disponivel', max_length=20)),
                ('planta_imagem', models.ImageField(blank=True, null=True, upload_to='unidades/plantas/')),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='empreendimentos.empreendimento')),
            ],
        ),
    ]
