# Generated by Django 5.2.3 on 2025-06-17 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoEmpreendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('revista', 'Revista Digital'), ('ficha', 'Ficha Técnica'), ('memorial', 'Memorial Descritivo'), ('contrato', 'Contrato Padrão'), ('tour_virtual', 'Tour Virtual')], max_length=20)),
                ('arquivo', models.FileField(blank=True, help_text='Para upload de arquivos PDF, JPG, etc.', null=True, upload_to='empreendimentos/documentos/')),
                ('link_externo', models.URLField(blank=True, help_text='Para links externos como o do Tour Virtual.', max_length=2048, null=True)),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='empreendimentos.empreendimento')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemEmpreendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(upload_to='empreendimentos/galeria/')),
                ('legenda', models.CharField(blank=True, max_length=255)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_galeria', to='empreendimentos.empreendimento')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='VideoEmpreendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_video', models.URLField(help_text='URL do vídeo (ex: YouTube, Vimeo)', max_length=2048)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('thumbnail', models.ImageField(upload_to='empreendimentos/thumbnails_video/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='empreendimentos.empreendimento')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
