# Generated by Django 5.2.3 on 2025-06-17 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0002_documentoempreendimento_imagemempreendimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltroLocalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaHabitacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpreendimentoFiltro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=2, help_text='Ex: 500', max_digits=10, null=True)),
                ('unidade_medida', models.CharField(blank=True, choices=[('m', 'metros'), ('km', 'km')], max_length=10, null=True)),
                ('texto_complementar', models.CharField(blank=True, help_text="Ex: 'Estação Tatuapé'", max_length=50)),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empreendimentos.empreendimento')),
                ('filtro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empreendimentos.filtrolocalizacao')),
            ],
            options={
                'unique_together': {('empreendimento', 'filtro')},
            },
        ),
        migrations.CreateModel(
            name='EmpreendimentoProgramaHabitacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empreendimentos.empreendimento')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empreendimentos.programahabitacional')),
            ],
            options={
                'unique_together': {('empreendimento', 'programa')},
            },
        ),
    ]
