# Generated by Django 5.2.3 on 2025-06-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0004_empreendimento_corretores_autorizados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='status_publicacao',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado')], default='rascunho', max_length=20),
        ),
    ]
