# Generated by Django 5.2.3 on 2025-06-18 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('empreendimentos', '0005_empreendimento_status_publicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('recusada', 'Recusada'), ('revogada', 'Revogada')], default='pendente', max_length=20)),
                ('data_convite', models.DateTimeField(auto_now_add=True)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcerias', to='empreendimentos.empreendimento')),
                ('imobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcerias', to='core.imobiliaria')),
            ],
            options={
                'unique_together': {('empreendimento', 'imobiliaria')},
            },
        ),
    ]
