# Generated by Django 5.2.3 on 2025-06-17 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empreendimentos', '0005_empreendimento_status_publicacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=255)),
                ('cpf_cliente', models.CharField(blank=True, max_length=14, null=True)),
                ('whatsapp_cliente', models.CharField(max_length=15)),
                ('email_cliente', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_contato', 'Em Contato'), ('qualificado', 'Qualificado'), ('desqualificado', 'Desqualificado'), ('convertido', 'Convertido')], default='novo', max_length=20)),
                ('origem', models.CharField(choices=[('organico', 'Orgânico (Site)'), ('link_corretor', 'Link de Corretor'), ('manual', 'Criação Manual')], default='organico', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_interacao', models.DateTimeField(auto_now=True)),
                ('corretor_atribuido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_atribuidos', to=settings.AUTH_USER_MODEL)),
                ('unidade_interesse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='empreendimentos.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='InteracaoLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_interacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(help_text='Usuário que registrou a interação', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='reservas.lead')),
            ],
            options={
                'ordering': ['-data_interacao'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('solicitada', 'Solicitada'), ('aprovada', 'Reserva Aceita'), ('docs_aguardando', 'Aguardando Documentação'), ('docs_aprovados', 'Documentação Aprovada'), ('contrato_enviado', 'Contrato Enviado'), ('contrato_recebido', 'Contrato Recebido'), ('venda_concluida', 'Venda Concluída'), ('cancelada', 'Cancelada')], default='solicitada', max_length=30)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to=settings.AUTH_USER_MODEL)),
                ('corretor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reserva', to='empreendimentos.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoStatusReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=30, null=True)),
                ('status_novo', models.CharField(max_length=30)),
                ('data_mudanca', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('mudado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='reservas.reserva')),
            ],
            options={
                'ordering': ['data_mudanca'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='reservas/documentos/')),
                ('nome_documento', models.CharField(max_length=255)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('uploaded_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='reservas.reserva')),
            ],
        ),
    ]
