# Generated by Django 5.2.3 on 2025-06-18 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='corretor_origem_link',
            field=models.ForeignKey(blank=True, help_text='Corretor que originou o lead através de um link de marketing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_gerados_por_link', to=settings.AUTH_USER_MODEL),
        ),
    ]
